<?php
/**
 * @file
 */

function blockfloat_form_block_admin_configure_alter(&$form, &$form_state, $form_id) {
  $blockfloat_block_config = variable_get(sprintf('blockfloat_block_%s_%s', arg(4), arg(5)), array());
  $form['#submit'][] = 'blockfloat_block_admin_configure_submit';
  $form['blockfloat_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => 'Display this block as a blockfloat Item',
    '#default_value' => isset($blockfloat_block_config['enabled']) ? $blockfloat_block_config['enabled'] : 0,
  );
}

function blockfloat_block_admin_configure_submit($form, &$form_state) {
  if (isset($form_state['values']['blockfloat_enabled'])) {
    $enabled = $form_state['values']['blockfloat_enabled'];
    $config = array('enabled' => $enabled);
    $delta = $form_state['values']['delta'];
    $module = $form_state['values']['module'];
    variable_set(sprintf('blockfloat_block_%s_%s', $module, $delta), $config);
  }
}

/**
 * Implements hook_preprocess_block()
 * @param $variables
 */
function blockfloat_preprocess_block(&$variables) {
  $block = $variables['block'];
  $blockfloat_block_config = variable_get(sprintf('blockfloat_block_%s_%s', $block->module, $block->delta), array());
  if (!empty($blockfloat_block_config['enabled'])) {
    drupal_add_css(drupal_get_path('module', 'blockfloat') . '/blockfloat.css');
    $variables['classes_array'][] = "blockfloat-block";
    $variables['classes_array'][] = "blockfloat-$block->delta";
  }
}
